variables:
# uncomment for the pipeline debug purpose
# CI_DEBUG_TRACE: "true"
  CI_IMAGE: $CI_GITLAB_REGISTRY_BASE/rd/linux-bsp/ci-toolchain-container/ci-toolchain-container:linux-toradex_aarch32_arm_builder-bb6f84e
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - when: never

stages:
  - build

repo-sync:
  stage: build
  image: $CI_IMAGE
  variables:
    GIT_STRATEGY: clone
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/toradex".insteadOf "https://gitlab.com/toradex"
  script:
    - ORIGIN=$(git remote get-url origin)
    - cd ..
    - mkdir -p bin
    - wget -O bin/repo https://commondatastorage.googleapis.com/git-repo-downloads/repo
    - chmod a+x bin/repo
    - mkdir -p workspace && cd workspace
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tdxref/default.xml
    - cp -rf ../toradex-manifest/* .repo/manifests/
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tdxref/integration.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tdxref/next.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tester/default.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tester/integration.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tester/next.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tezi/default.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tezi/integration.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m tezi/next.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m torizoncore/default.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m torizoncore/integration.xml
    - ../bin/repo sync
    - ../bin/repo init -u $ORIGIN -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME -m torizoncore/next.xml
    - ../bin/repo sync
